packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
overrides:
  '@gitsang/dsh-web-auth': link:../../../src/github.com/gitsang/dsh-web-auth
  '@gitsang/dsh-fishing': link:../../../src/github.com/gitsang/dsh-fishing
